'use strict';
const express = require('express');
const app = express();
const port = 3000;
const cats = require('./routes/catRoute');
const users = require('./routes/userRoute');
const passport = require('./utils/pass');
const authRoute = require('./routes/authRoute');
const cors = require('cors');
const bodyParser = require('body-parser');

app.use('/cat', cats);
app.use('/user', users);
app.use('/auth', authRoute);
app.use('/cat', passport.authenticate('jwt', {session: false}), cats);
app.use('/user', passport.authenticate('jwt', {session: false}), users);
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
app.listen(port, () => console.log('Example app listening on port ${port}!'));
